export const ROUTER = {
  LANDING: 'LANDING',
  SPLASH: 'SPLASH',
  HOME_NAV: 'HOME_NAV',
  PDP: 'PDP',
  CART: 'CART',
  CHECKOUT: 'CHECKOUT',
  PLP: 'PLP',
  ACCOUNT: 'ACCOUNT',
  ORDERS: 'ORDERS',
  ORDER_DETAILS: 'ORDER_DETAILS',
  WISHLIST: 'WISHLIST',
  ADDRESSES: 'ADDRESSES',
  SETTINGS: 'SETTINGS',
  HOME: 'HOME',
  CATEGORIES: 'CATEGORIES',
  CREATE_EDIT_ADDRESS: 'CREATE_EDIT_ADDRESS',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
};

export type RootStackParamList = {
  LANDING: any;
  SPLASH: any;
  HOME_NAV: any;
  PDP: any;
  CART: any;
  CHECKOUT: any;
  PLP: any;
  ACCOUNT: any;
  ORDERS: any;
  ORDER_DETAILS: any;
  WISHLIST: any;
  ADDRESSES: any;
  SETTINGS: any;
  HOME: any;
  CATEGORIES: any;
  CREATE_EDIT_ADDRESS: any;
  CHANGE_PASSWORD: any;
};
